// in profile/EditProfile.jso
import React from 'react';
import { Edit, TextInput, SimpleForm, required, TextField,
    ImageInput,
    DateInput,
    SelectInput,
    ImageField,} from 'react-admin';

function formatPicture(value) {
    if (!value || typeof value === "string") {
      return { picture: value };
    } else {
      return value;
    }
}
  
const ProfileEdit = ({ staticContext, ...props }) => {
  return (
      <Edit
            /*
                As this component isn't loaded from a route generated by a <Resource>,
                I have to provide the id myself.
                As there is only one config for the current user, I decided to
                hard-code it here
            */
            id="my-profile"
            /*
                For the same reason, I need to provide the resource and basePath props
                which are required by the Edit component
            */
            resource="profile"
            basePath="/my-profile"
            /*
                I also customized the page title as it'll make more sense to the user
            */
            title="My profile"
            redirect={false} // I don't need any redirection here, there's no list page
            {...props}
        >
        <SimpleForm redirect="show" submitOnEnter={true}>
          <ImageInput format={formatPicture} source="picture" accept="image/*">
            <ImageField source="picture" />
          </ImageInput>
          <TextInput source="name" />
          {/* <TextInput source="id" /> */}
          <TextInput source="phoneNumber" />
          <SelectInput
            source="gender"
            choices={[
              { id: "FEMALE", name: "FEMALE" },
              { id: "MALE", name: "MALE" },
              { id: "OTHER", name: "OTHER" },
            ]}
          />
          <DateInput label="Date Of Birth" source="dateOfBirth" />
          <TextInput source="city" />
          <TextInput source="country" />
        </SimpleForm>
      </Edit>
  );
};

export default ProfileEdit;